export const categories = [
  {
    category: "Accessories",
    imagePath: "/categories/accessories.jpeg",
    subCategory: [],
  },
  {
    category: "Medical Consumables",
    imagePath: "/categories/medicalConsumables.jpeg",
    subCategory: [],
  },
  {
    category: "Hospital Equipment",
    imagePath: "/categories/hospitalEquipment.jpeg",
    subCategory: [],
  },
  {
    category: "Laboratory Equipment",
    imagePath: "/categories/laboratoryEquipment.jpeg",
    subCategory: [
      "Clinical Chemistry",
      "Hematology Unit",
      "Histopathologys",
      "Microbiology",
      "Molecular Biology",
      "Virology Unit",
    ],
  },

  {
    category: "Medical Equipment",
    imagePath: "/categories/medicalEquipment.png",
    subCategory: [
      "Accident & Emergency",
      "Anesthesiology",
      "Cardiology",
      "Cryosurgery",
      "Dental Unit",
      "Internal Medicine",
      "Obstetrics & Gynecology",
      "Oncology",
      "Ophthamology",
      "Orthopedic Unit",
      "Pediatric",
      "Physiotherapy",
      "Psychiatric",
      "Radiology",
      "Surgery Unit",
      "Urology",
    ],
  },
  {
    category: "Medical Furniture",
    imagePath: "/categories/medicalFurniture.jpeg",
    subCategory: [
      "Bed",
      "Examination",
      "Light",
      "Pediatric Bed",
      "Stretcher",
      "Trolley",
    ],
  },
  {
    category: "Neurology",
    imagePath: "/categories/neurology.jpeg",
    subCategory: [],
  },
  {
    category: "Scientific & Medical Education",
    imagePath: "/categories/scienceEducation.jpeg",
    subCategory: [
      "Biology Experiments",
      "Chemistry Models",
      "Chemistry-Experiments",
      "Earth Science",
      "Health Education",
      "Human Anatomy Models",
      "Medical Charts",
      "Medical Simulators",
      "Physics Experiments",
    ],
  },
  {
    category: "Surgical Hand Instrument",
    imagePath: "/categories/surgeryEquipment.jpeg",
    subCategory: [],
  },
  {
    category: "Veterinary Medicine",
    imagePath: "/categories/veterinaryEquipment.jpeg",
    subCategory: [],
  },
]
