export const categories = [
  {
    category: "Laboratory Equipment",
    imagePath: "/categories/laboratoryEquipment.jpeg",
    isActive: false,
    subCategory: [
      "High Speed Freeze Centrifuge",
      "Low Speed Freeze Centrifuge",
      "Special Centrifuge",
      "Laboratory Shaker",
      "Blood Roller Mixer",
      "Water Distiller 5L",
      "Water Distiller 10L",
      "Water Distiller 5L",
      "Magnetic and Electric Stirrer",
      "Laboratory Incubator",
      "Dry Oven",
      "PH Meter",
      "Biological Safety Cabinet",
      "Laminar Flow Cabinet",
      "Portable Autoclave (24L)",
      "Autoclave (steam sterilizer), 35L",
      "Autoclave (steam sterilizer), 50L",
      "Ultrasonic Cleaner",
      "Fixed Micropipette",
      "Variable Micropipette",
      "Rotatory Microtome",
      "Wash Hand Stand (Single Bow)",
      "Wash Hand Stand (Double bow)",
      "Medical Freezer",
      "Blood Bank Refrigerator",
      "Medical Pharmacy Refrigerator",
      "Electronic Analytical Balance",
      "Medical Destroyer",
      "Hand-Held ETCO2",
      "Blood Glucose Monitor",
      "Haematology Analyzer (3 Parts)",
      "Haematology Analyzer (5 Parts)",
      "Chemistry Analyzer (Semi auto)",
      "Biological Microscope",
      "Spectrophotometer",
      "High Speed Centrifuge",
    ],
  },
  {
    category: "Hospital Furniture",
    imagePath: "/categories/medicalFurniture.jpeg",
    isActive: false,
    subCategory: [
      "1-Function Manual Hospital Bed",
      "2-Function Hospital Bed",
      "3-Function Hospital Bed",
      "Electric Hospital Bed",
      "ICU Bed",
      "Children's Hospital Bed",
      "Hospital Baby Crib",
      "Emergency/Medicine Trolley",
      "Doctor's Chair",
      "Doctor's stool",
      "Sleeping Chair",
      "Infusion Chair",
      "Drip stand",
      "Four Folding Wall Screen",
      "Bedside Cabinet (Iron)",
      "Bedside Cabinet (Steel)",
      "Patient trolley",
      "Emergency Stretcher",
      "Instrument trolley with two drawers",
      "Instrument Trolley without Drawer",
      "Instrument Trolley with Three Steps",
      "Folding Stretcher",
      "Appliance Cupboard",
      "Examination Couch",
      "Bedsore prevention Mattress",
      "Overbed Table",
      "Ward Equipment",
      "Orthopedic Bed",
      "Mattress",
      "Patient Step",
    ],
  },
  {
    category: "Walking Aid/Orthopaedics",
    imagePath: "/categories/surgeryEquipment.jpeg",
    isActive: false,
    subCategory: [
      "Aluminum Wheelchair",
      "Lightweight Wheelchair",
      "Transport Wheelchair",
      "Steel Wheelchair",
      "Abdominal Support",
      "Tummy Trimmer Abdominal",
      "LS Belt Lumbopore",
      "Lumbo Sacral Belt",
      "Contoured L.S. Support",
      "Rib Belt",
      "Chest Binder",
      "Lumbo Support Uni",
      "Pregnancy Back Support",
      "Lumbo Lacepull Brace",
      "Taylor's Brace Short / Long",
      "Ash Brace (Hyper Extension Brace)",
      "Hernia Belt",
      "Cervical Collar Soft",
      "Cervical Collar Soft with Support",
      "Collar Soft (Firm Density)",
      "Cervical Orthosis (Philadelphia) Ethafoam",
      "Cervical Collar Hard Adjustable",
      "Cervical Collar Hard With Chin",
      "Cervical Pillow Regular",
      "Pouch Arm Sling (Tropical)",
      "Pouch Arm Sling (Baggy)",
      "Universal Shoulder immobilizer",
      "Clavicle Brace with Buckle",
      "Elastic Shoulder Immobilizer",
      "USPs- Cast Shoe (Rocker Sole)",
      "Cast cover (Leg)",
      "Ankle Binder",
      "Anklet Comfeel (Pair)",
      "Anklet (Pair)",
      "Knee Cap (Pair)",
      "Small Quad Cane",
      "Large Quad Cane",
      "Quad Cane",
      "Tripod Cane",
      "Cap (with Rigid Hinge)",
      "Knee",
      "Knee Cap with Patellar Ring",
      "Elastic Wrist Splint Right/Left",
      "Wrist Splint Ambidextrous",
      "Wrist Splint with Thumb",
      "Wrist Brace with Double Lock",
      "Elbow Support",
      "Hand Resting Splint Right/Left",
      "ROM Elbow Brace",
      "Finger Cot",
      "Finger Ext. Splint",
      "Thumb Spica Splint",
      "Cervical Traction Kit (Sitting) with Weight Bag",
      "Skin Traction Set (PUF Liner)",
      "Cervical Traction Kit (Sitting) with Weight Bag",
      "Weight Cuff",
      "Hot & Cold Pack",
      "Restrainer",
      "Back Rest",
      "Ortho Stockinete",
      "Compression Stocking Mid Thig",
      "Anti Embolism Stockings",
      "Knee Support Hinged (Neoprene)",
      "Ankle Support (Neoprene)",
      "Abs Wrap (Neoprene)",
      "Wrist Brace with Thumb (Neoprene)",
      "Insole Omni Silicone (Pair)",
      "Heel Cup Silicone (Pair)",
      "Bunion Splint",
      "Medial Arch Orthosis (Pair) Child",
      "Pouch Arm Sling (Oxypore)",
      "Reclining Wheelchair",
    ],
  },
  {
    category: "Accessories",
    imagePath: "/categories/accessories.jpeg",
    subCategory: [],
  },
  {
    category: "Medical Consumables",
    imagePath: "/categories/medicalConsumables.jpeg",
    subCategory: [],
  },
]
