export const groups = [
  {
    group: "TRANSMISSION",
    categories: [
      "Drive-In Cinema FM Transmitter Sets",
      "FM Transmitters",
      "Digital Radio DAB/DAB+",
      "TV Transmitters + Accessories",
      "AM / SW Transmitters",
      "RDS & Stereo Encoder",
      "Satellite Equipment",
      "Antennas & Filters",
      "ON AIR Broadcast Processors",
      "RF Radio Links Audio + Video",
      "Antenna Masts and Towers",
      "FM & DAB Receivers & Re-broadcast",
      "RF Cable & Connectors",
      "Radio communication",
      "Dummy Loads",
      "RF Monitoring/Measuring",
    ],
  },
  {
    group: "RADIO EQUIPMENT",
    categories: [
      "Mixers / Consoles",
      "RF Tools",
      "Microphones",
      "Headphones",
      "Headsets",
      "Studio Monitor Speakers",
      "Radio Software",
      "Radio Turnkey Solutions",
      "IP & ISDN Audio Codecs",
      "Audio Cards & Interfaces",
      "Stands Mic + Monitor",
      "Studio Furniture",
      "Studio accessories",
      "Reporter & Commentator Equip",
    ],
  },
  {
    group: "TV EQUIPMENT",
    categories: [
      "TV Software & Systems",
      "TV Turnkey Solutions",
      "TV Mixers Switchers Routers",
      "Cameras & Accessories",
      "Lights",
      "Microphones for TV",
      "Video IP Transmission",
      "Video Converters",
      "Video Monitors",
      "TV Production accessories",
      "Video Miscellaneous",
    ],
  },
  {
    group: "MISCELLANEOUS",
    categories: [
      "Racks and Housing",
      "Audio Amplifiers",
      "Used Transmitters",
      "Computers + Servers",
      "Network + Wireless",
      "PA Speakers",
      "UPS / Stabilizers / Protection",
      "GSM Repeaters",
      "Electronics Misc",
      "X",
    ],
  },
]
