import Head from 'next/head'
import styled from "styled-components";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-primary text-center'>
        Welcome to Vetox Global Medical
      </h1>
    </Container>
  );
}

const Container = styled.div`
  height: 100vh;
`;